version: '3.8'

services:
  dev:
    container_name: obc_connector_dev
    image: obc-connector-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 5818:3000
    networks:
      - obc-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - redis
  prod:
    container_name: obc_connector_prod
    image: obc-connector-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 5818:3000
    networks:
      - obc-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    container_name: obc-redis-cache
    image: redis
    ports:
      - 5004:6379
    networks:
      - obc-network

networks:
  obc-network:
